version: "3.3"
services:
  app:
    image: python:3.8
    working_dir: /app
    command: bash -c 'pip install -r requirements.txt && tail -f /dev/null'
    volumes:
      - .:/app
      - ./keys:/root/.ssh
